run_name: OLMo-1B
seed: 6198
dry_run: false

wandb:
  name: olma_2layer_dsir_sampled_14ep_0.6B
  project: scaling_laws

model:
  d_model: 2048
  n_heads: 16
  n_layers: 2
  mlp_ratio: 8
  weight_tying: true
  alibi: false
  rope: true
  flash_attention: false  # not available on AMD
  attention_dropout: 0.0
  attention_layer_norm: false
  multi_query_attention: false
  include_bias: false
  block_type: sequential
  layer_norm_type: default
  layer_norm_with_affine: false
  bias_for_layer_norm: false
  attention_layer_norm_with_affine: false
  activation_type: swiglu
  residual_dropout: 0.0
  embedding_dropout: 0.0
  max_sequence_length: 2048
  vocab_size: 50280
  embedding_size: 50304
  eos_token_id: 50279
  pad_token_id: 1
  init_device: meta
  init_fn: mitchell

compile: null  # causes instability on AMD GPUs

optimizer:
  name: adamw
  learning_rate: 4.0e-4
  weight_decay: 0.1
  betas:
  - 0.9
  - 0.95
  metrics_log_interval: 10

scheduler:
  name: cosine_with_warmup
  t_warmup: 2000
  alpha_f: 0.1

tokenizer:
  identifier: OLMo/tokenizers/allenai_eleuther-ai-gpt-neox-20b-pii-special.json
  truncate_direction: right

save_folder: pre_training_results/olma/14ep/2_layer_0.6B_dsir
save_overwrite: True
# Sharded checkpoints (best for restarts)
save_interval: 1000
save_num_checkpoints_to_keep: 9
# Unsharded checkpoints (for final storage)
save_interval_unsharded: 10000
save_num_unsharded_checkpoints_to_keep: 1

load_path: null

max_duration: 14ep  
global_train_batch_size: 2048
device_train_microbatch_size: 36

precision: amp_bf16

fsdp:
  wrapping_strategy: null
  precision: mixed

max_grad_norm: 1.0
max_grad_norm_ratio: null

speed_monitor:
  window_size: 20

eval_interval: 10000 # actually steps = ~7000, so we don't run eval on-line
eval_subset_num_batches: -1
device_eval_batch_size: ${device_train_microbatch_size}
evaluators:
  # lump all the small datasets together (we still get separate metrics).
  - label: v3-small-ppl-validation
    data:
      num_workers: 0
      drop_last: true
      datasets:
        v3-small-c4_en-validation:
          - data/dolma/olma_1B_data/val_data/v3-small-c4_en-validation/part-0-00000.npy

  - label: v2-small-ppl-validation
    data:
      num_workers: 0
      drop_last: true
      datasets:
        v2-small-4chan-validation:
          - data/dolma/olma_1B_data/val_data/v2-small-4chan-validation/val.npy

  # - label: piqa
  #   type: downstream

  # - label: hellaswag
  #   type: downstream

  # - label: winogrande
  #   type: downstream

  # - label: openbook_qa
  #   type: downstream

  # - label: boolq  # requires implemention of the pmi_dc matrix
    # type: downstream

  # - label: sciq
  #   type: downstream

  # - label: arc_easy
  #   type: downstream

  # - label: arc_challenge  # requires implemention of the pmi_dc matrix
  #   type: downstream

  # - label: copa
  #   type: downstream

  # - label: rte
  #   type: downstream

  # - label: commitment_bank
  #   type: downstream

  # - label: mrpc
  #   type: downstream

  # - label: sst2
  #   type: downstream

data:
  pad_direction: right
  num_workers: 0
  drop_last: true
  pin_memory: true
  prefetch_factor: 16
  persistent_workers: true
  timeout: 0
  paths:
    - data/dsir_sampled/1M_cosmopedia_tokenized/000_00000.npy
    - data/dsir_sampled/1M_cosmopedia_tokenized/001_00000.npy
    - data/dsir_sampled/1M_cosmopedia_tokenized/002_00000.npy
    - data/dsir_sampled/1M_cosmopedia_tokenized/003_00000.npy
    - data/dsir_sampled/1M_cosmopedia_tokenized/004_00000.npy
    - data/dsir_sampled/1M_cosmopedia_tokenized/005_00000.npy
    - data/dsir_sampled/1M_cosmopedia_tokenized/006_00000.npy
    - data/dsir_sampled/1M_cosmopedia_tokenized/007_00000.npy
    - data/dsir_sampled/1M_cosmopedia_tokenized/008_00000.npy
    - data/dsir_sampled/1M_cosmopedia_tokenized/009_00000.npy
    - data/dsir_sampled/1M_cosmopedia_tokenized/010_00000.npy
    - data/dsir_sampled/1M_cosmopedia_tokenized/011_00000.npy
    - data/dsir_sampled/1M_cosmopedia_tokenized/012_00000.npy
    - data/dsir_sampled/1M_cosmopedia_tokenized/013_00000.npy
    - data/dsir_sampled/1M_cosmopedia_tokenized/014_00000.npy
    - data/dsir_sampled/1M_cosmopedia_tokenized/015_00000.npy
    - data/dsir_sampled/1M_cosmopedia_tokenized/016_00000.npy
    - data/dsir_sampled/1M_cosmopedia_tokenized/017_00000.npy
    - data/dsir_sampled/1M_cosmopedia_tokenized/018_00000.npy
    - data/dsir_sampled/1M_cosmopedia_tokenized/019_00000.npy
    - data/dsir_sampled/1M_cosmopedia_tokenized/020_00000.npy
    - data/dsir_sampled/1M_cosmopedia_tokenized/021_00000.npy
    - data/dsir_sampled/1M_cosmopedia_tokenized/022_00000.npy
    - data/dsir_sampled/1M_cosmopedia_tokenized/023_00000.npy
    - data/dsir_sampled/1M_cosmopedia_tokenized/024_00000.npy
    - data/dsir_sampled/1M_cosmopedia_tokenized/025_00000.npy
    - data/dsir_sampled/1M_cosmopedia_tokenized/026_00000.npy
    - data/dsir_sampled/1M_cosmopedia_tokenized/027_00000.npy
    - data/dsir_sampled/1M_cosmopedia_tokenized/028_00000.npy
    - data/dsir_sampled/1M_cosmopedia_tokenized/029_00000.npy
    - data/dsir_sampled/1M_cosmopedia_tokenized/030_00000.npy
    - data/dsir_sampled/1M_cosmopedia_tokenized/031_00000.npy
    - data/dsir_sampled/1M_cosmopedia_tokenized/032_00000.npy
    - data/dsir_sampled/1M_cosmopedia_tokenized/033_00000.npy
    - data/dsir_sampled/1M_cosmopedia_tokenized/034_00000.npy
    - data/dsir_sampled/1M_cosmopedia_tokenized/035_00000.npy
    - data/dsir_sampled/1M_cosmopedia_tokenized/036_00000.npy
    - data/dsir_sampled/1M_cosmopedia_tokenized/037_00000.npy
    - data/dsir_sampled/1M_cosmopedia_tokenized/038_00000.npy
    - data/dsir_sampled/1M_cosmopedia_tokenized/039_00000.npy
    - data/dsir_sampled/1M_cosmopedia_tokenized/040_00000.npy
    - data/dsir_sampled/1M_cosmopedia_tokenized/041_00000.npy
    - data/dsir_sampled/1M_cosmopedia_tokenized/042_00000.npy
    - data/dsir_sampled/1M_cosmopedia_tokenized/043_00000.npy
    - data/dsir_sampled/1M_cosmopedia_tokenized/044_00000.npy
    - data/dsir_sampled/1M_cosmopedia_tokenized/045_00000.npy
    - data/dsir_sampled/1M_cosmopedia_tokenized/046_00000.npy
    - data/dsir_sampled/1M_cosmopedia_tokenized/047_00000.npy
    - data/dsir_sampled/1M_cosmopedia_tokenized/048_00000.npy
    - data/dsir_sampled/1M_cosmopedia_tokenized/049_00000.npy
    - data/dsir_sampled/1M_cosmopedia_tokenized/050_00000.npy
    - data/dsir_sampled/1M_cosmopedia_tokenized/051_00000.npy
    - data/dsir_sampled/1M_cosmopedia_tokenized/052_00000.npy
    - data/dsir_sampled/1M_cosmopedia_tokenized/053_00000.npy
    - data/dsir_sampled/1M_cosmopedia_tokenized/054_00000.npy
    - data/dsir_sampled/1M_cosmopedia_tokenized/055_00000.npy
    - data/dsir_sampled/1M_cosmopedia_tokenized/056_00000.npy
    - data/dsir_sampled/1M_cosmopedia_tokenized/057_00000.npy
    - data/dsir_sampled/1M_cosmopedia_tokenized/058_00000.npy
    - data/dsir_sampled/1M_cosmopedia_tokenized/059_00000.npy
    - data/dsir_sampled/1M_cosmopedia_tokenized/060_00000.npy
    - data/dsir_sampled/1M_cosmopedia_tokenized/061_00000.npy
    - data/dsir_sampled/1M_cosmopedia_tokenized/062_00000.npy
    - data/dsir_sampled/1M_cosmopedia_tokenized/063_00000.npy
    - data/dsir_sampled/1M_cosmopedia_tokenized/064_00000.npy
    - data/dsir_sampled/1M_cosmopedia_tokenized/065_00000.npy
    - data/dsir_sampled/1M_cosmopedia_tokenized/066_00000.npy
    - data/dsir_sampled/1M_cosmopedia_tokenized/067_00000.npy
    - data/dsir_sampled/1M_cosmopedia_tokenized/068_00000.npy
    - data/dsir_sampled/1M_cosmopedia_tokenized/069_00000.npy
    - data/dsir_sampled/1M_cosmopedia_tokenized/070_00000.npy
    - data/dsir_sampled/1M_cosmopedia_tokenized/071_00000.npy
    - data/dsir_sampled/1M_cosmopedia_tokenized/072_00000.npy
    - data/dsir_sampled/1M_cosmopedia_tokenized/073_00000.npy
    - data/dsir_sampled/1M_cosmopedia_tokenized/074_00000.npy
    - data/dsir_sampled/1M_cosmopedia_tokenized/075_00000.npy
    - data/dsir_sampled/1M_cosmopedia_tokenized/076_00000.npy
    - data/dsir_sampled/1M_cosmopedia_tokenized/077_00000.npy
    - data/dsir_sampled/1M_cosmopedia_tokenized/078_00000.npy
    - data/dsir_sampled/1M_cosmopedia_tokenized/079_00000.npy
    - data/dsir_sampled/1M_cosmopedia_tokenized/080_00000.npy
    - data/dsir_sampled/1M_cosmopedia_tokenized/081_00000.npy
    - data/dsir_sampled/1M_cosmopedia_tokenized/082_00000.npy
    - data/dsir_sampled/1M_cosmopedia_tokenized/083_00000.npy
    - data/dsir_sampled/1M_cosmopedia_tokenized/084_00000.npy
    - data/dsir_sampled/1M_cosmopedia_tokenized/085_00000.npy
    - data/dsir_sampled/1M_cosmopedia_tokenized/086_00000.npy
    - data/dsir_sampled/1M_cosmopedia_tokenized/087_00000.npy
    - data/dsir_sampled/1M_cosmopedia_tokenized/088_00000.npy
    - data/dsir_sampled/1M_cosmopedia_tokenized/089_00000.npy
    - data/dsir_sampled/1M_cosmopedia_tokenized/090_00000.npy
    - data/dsir_sampled/1M_cosmopedia_tokenized/091_00000.npy
    - data/dsir_sampled/1M_cosmopedia_tokenized/092_00000.npy
    - data/dsir_sampled/1M_cosmopedia_tokenized/093_00000.npy
    - data/dsir_sampled/1M_cosmopedia_tokenized/094_00000.npy
    - data/dsir_sampled/1M_cosmopedia_tokenized/095_00000.npy
    - data/dsir_sampled/1M_cosmopedia_tokenized/096_00000.npy
    - data/dsir_sampled/1M_cosmopedia_tokenized/097_00000.npy
    - data/dsir_sampled/1M_cosmopedia_tokenized/098_00000.npy
    - data/dsir_sampled/1M_cosmopedia_tokenized/099_00000.npy

