run_name: OLMo-1B
seed: 6198
dry_run: false

wandb:
  name: olma_2layer_mixdata_0.75_1_ep
  project: scaling_laws

model:
  d_model: 2048
  n_heads: 16
  n_layers: 2
  mlp_ratio: 8
  weight_tying: true
  alibi: false
  rope: true
  flash_attention: false  # not available on AMD
  attention_dropout: 0.0
  attention_layer_norm: false
  multi_query_attention: false
  include_bias: false
  block_type: sequential
  layer_norm_type: default
  layer_norm_with_affine: false
  bias_for_layer_norm: false
  attention_layer_norm_with_affine: false
  activation_type: swiglu
  residual_dropout: 0.0
  embedding_dropout: 0.0
  max_sequence_length: 2048
  vocab_size: 50280
  embedding_size: 50304
  eos_token_id: 50279
  pad_token_id: 1
  init_device: meta
  init_fn: mitchell

compile: null  # causes instability on AMD GPUs

optimizer:
  name: adamw
  learning_rate: 4.0e-4
  weight_decay: 0.1
  betas:
  - 0.9
  - 0.95
  metrics_log_interval: 10

scheduler:
  name: cosine_with_warmup
  t_warmup: 2000
  alpha_f: 0.1

tokenizer:
  identifier: OLMo/tokenizers/allenai_eleuther-ai-gpt-neox-20b-pii-special.json
  truncate_direction: right

save_folder: pre_training_results/olma/1ep/mixdata_0.75
save_overwrite: True
# Sharded checkpoints (best for restarts)
save_interval: 1000
save_num_checkpoints_to_keep: 9
# Unsharded checkpoints (for final storage)
save_interval_unsharded: 10000
save_num_unsharded_checkpoints_to_keep: 1

load_path: null

max_duration: 1ep  
global_train_batch_size: 2048
device_train_microbatch_size: 36

precision: amp_bf16

fsdp:
  wrapping_strategy: null
  precision: mixed

max_grad_norm: 1.0
max_grad_norm_ratio: null

speed_monitor:
  window_size: 20

eval_interval: 10000 # actually steps = ~7000, so we don't run eval on-line
eval_subset_num_batches: -1
device_eval_batch_size: ${device_train_microbatch_size}
evaluators:
  # lump all the small datasets together (we still get separate metrics).
  - label: v3-small-ppl-validation
    data:
      num_workers: 0
      drop_last: true
      datasets:
        v3-small-c4_en-validation:
          - data/dolma/olma_1B_data/val_data/v3-small-c4_en-validation/part-0-00000.npy

  - label: v2-small-ppl-validation
    data:
      num_workers: 0
      drop_last: true
      datasets:
        v2-small-4chan-validation:
          - data/dolma/olma_1B_data/val_data/v2-small-4chan-validation/val.npy

  # - label: piqa
  #   type: downstream

  # - label: hellaswag
  #   type: downstream

  # - label: winogrande
  #   type: downstream

  # - label: openbook_qa
  #   type: downstream

  # - label: boolq  # requires implemention of the pmi_dc matrix
    # type: downstream

  # - label: sciq
  #   type: downstream

  # - label: arc_easy
  #   type: downstream

  # - label: arc_challenge  # requires implemention of the pmi_dc matrix
  #   type: downstream

  # - label: copa
  #   type: downstream

  # - label: rte
  #   type: downstream

  # - label: commitment_bank
  #   type: downstream

  # - label: mrpc
  #   type: downstream

  # - label: sst2
  #   type: downstream

data:
  pad_direction: right
  num_workers: 0
  drop_last: true
  pin_memory: true
  prefetch_factor: 16
  persistent_workers: true
  timeout: 0
  paths:
    - data/cosmopedia/cosmopedia_sampled/8B_tokenize_2048/021_00000.npy
    - data/dolma/olma_tokenize/014_00000.npy
    - data/dolma/olma_tokenize/087_00000.npy
    - data/cosmopedia/cosmopedia_sampled/8B_tokenize_2048/065_00000.npy
    - data/cosmopedia/cosmopedia_sampled/8B_tokenize_2048/045_00000.npy
    - data/dolma/olma_tokenize/098_00000.npy
    - data/dolma/olma_tokenize/047_00000.npy
    - data/dolma/olma_tokenize/045_00000.npy
    - data/cosmopedia/cosmopedia_sampled/8B_tokenize_2048/062_00000.npy
    - data/dolma/olma_tokenize/056_00000.npy
    - data/cosmopedia/cosmopedia_sampled/8B_tokenize_2048/036_00000.npy
    - data/cosmopedia/cosmopedia_sampled/8B_tokenize_2048/033_00000.npy
    - data/cosmopedia/cosmopedia_sampled/8B_tokenize_2048/018_00000.npy
    - data/cosmopedia/cosmopedia_sampled/8B_tokenize_2048/041_00000.npy
    - data/dolma/olma_tokenize/003_00000.npy
    - data/dolma/olma_tokenize/041_00000.npy
    - data/dolma/olma_tokenize/052_00000.npy
    - data/dolma/olma_tokenize/076_00000.npy
    - data/cosmopedia/cosmopedia_sampled/8B_tokenize_2048/016_00000.npy
    - data/cosmopedia/cosmopedia_sampled/8B_tokenize_2048/056_00000.npy
    - data/cosmopedia/cosmopedia_sampled/8B_tokenize_2048/038_00000.npy
    - data/cosmopedia/cosmopedia_sampled/8B_tokenize_2048/066_00000.npy
    - data/cosmopedia/cosmopedia_sampled/8B_tokenize_2048/053_00000.npy
    - data/cosmopedia/cosmopedia_sampled/8B_tokenize_2048/013_00000.npy
    - data/dolma/olma_tokenize/080_00000.npy
    - data/cosmopedia/cosmopedia_sampled/8B_tokenize_2048/025_00000.npy
    - data/cosmopedia/cosmopedia_sampled/8B_tokenize_2048/019_00000.npy
    - data/cosmopedia/cosmopedia_sampled/8B_tokenize_2048/011_00000.npy
    - data/cosmopedia/cosmopedia_sampled/8B_tokenize_2048/052_00000.npy
    - data/cosmopedia/cosmopedia_sampled/8B_tokenize_2048/004_00000.npy
    - data/cosmopedia/cosmopedia_sampled/8B_tokenize_2048/027_00000.npy
    - data/cosmopedia/cosmopedia_sampled/8B_tokenize_2048/014_00000.npy
    - data/cosmopedia/cosmopedia_sampled/8B_tokenize_2048/008_00000.npy
    - data/cosmopedia/cosmopedia_sampled/8B_tokenize_2048/051_00000.npy
    - data/cosmopedia/cosmopedia_sampled/8B_tokenize_2048/044_00000.npy
    - data/cosmopedia/cosmopedia_sampled/8B_tokenize_2048/022_00000.npy
    - data/cosmopedia/cosmopedia_sampled/8B_tokenize_2048/058_00000.npy
    - data/cosmopedia/cosmopedia_sampled/8B_tokenize_2048/048_00000.npy
    - data/cosmopedia/cosmopedia_sampled/8B_tokenize_2048/034_00000.npy
    - data/dolma/olma_tokenize/016_00000.npy
    - data/dolma/olma_tokenize/085_00000.npy
    - data/dolma/olma_tokenize/017_00000.npy
    - data/cosmopedia/cosmopedia_sampled/8B_tokenize_2048/039_00000.npy
    - data/dolma/olma_tokenize/082_00000.npy
    - data/cosmopedia/cosmopedia_sampled/8B_tokenize_2048/028_00000.npy
    - data/dolma/olma_tokenize/027_00000.npy
    - data/dolma/olma_tokenize/077_00000.npy
    - data/cosmopedia/cosmopedia_sampled/8B_tokenize_2048/035_00000.npy
    - data/cosmopedia/cosmopedia_sampled/8B_tokenize_2048/032_00000.npy
    - data/cosmopedia/cosmopedia_sampled/8B_tokenize_2048/020_00000.npy
    - data/cosmopedia/cosmopedia_sampled/8B_tokenize_2048/015_00000.npy
    - data/cosmopedia/cosmopedia_sampled/8B_tokenize_2048/037_00000.npy
    - data/cosmopedia/cosmopedia_sampled/8B_tokenize_2048/023_00000.npy
    - data/dolma/olma_tokenize/022_00000.npy
    - data/cosmopedia/cosmopedia_sampled/8B_tokenize_2048/000_00000.npy
    - data/cosmopedia/cosmopedia_sampled/8B_tokenize_2048/046_00000.npy
    - data/dolma/olma_tokenize/032_00000.npy
    - data/dolma/olma_tokenize/093_00000.npy
    - data/cosmopedia/cosmopedia_sampled/8B_tokenize_2048/006_00000.npy
    - data/dolma/olma_tokenize/078_00000.npy
    - data/dolma/olma_tokenize/092_00000.npy
    - data/cosmopedia/cosmopedia_sampled/8B_tokenize_2048/026_00000.npy
    - data/dolma/olma_tokenize/051_00000.npy
    - data/cosmopedia/cosmopedia_sampled/8B_tokenize_2048/007_00000.npy
    - data/cosmopedia/cosmopedia_sampled/8B_tokenize_2048/050_00000.npy
    - data/cosmopedia/cosmopedia_sampled/8B_tokenize_2048/043_00000.npy
    - data/cosmopedia/cosmopedia_sampled/8B_tokenize_2048/012_00000.npy
    - data/cosmopedia/cosmopedia_sampled/8B_tokenize_2048/064_00000.npy
    - data/dolma/olma_tokenize/060_00000.npy
    - data/cosmopedia/cosmopedia_sampled/8B_tokenize_2048/057_00000.npy
    - data/cosmopedia/cosmopedia_sampled/8B_tokenize_2048/059_00000.npy
    - data/dolma/olma_tokenize/043_00000.npy
    - data/cosmopedia/cosmopedia_sampled/8B_tokenize_2048/055_00000.npy
    - data/cosmopedia/cosmopedia_sampled/8B_tokenize_2048/002_00000.npy
    - data/cosmopedia/cosmopedia_sampled/8B_tokenize_2048/054_00000.npy

