run_name: OLMo-1B
seed: 6198
dry_run: false

wandb:
  name: olma_2layer_dolma_25B
  project: scaling_laws

model:
  d_model: 2048
  n_heads: 16
  n_layers: 2
  mlp_ratio: 8
  weight_tying: true
  alibi: false
  rope: true
  flash_attention: false  # not available on AMD
  attention_dropout: 0.0
  attention_layer_norm: false
  multi_query_attention: false
  include_bias: false
  block_type: sequential
  layer_norm_type: default
  layer_norm_with_affine: false
  bias_for_layer_norm: false
  attention_layer_norm_with_affine: false
  activation_type: swiglu
  residual_dropout: 0.0
  embedding_dropout: 0.0
  max_sequence_length: 2048
  vocab_size: 50280
  embedding_size: 50304
  eos_token_id: 50279
  pad_token_id: 1
  init_device: meta
  init_fn: mitchell

compile: null  # causes instability on AMD GPUs

optimizer:
  name: adamw
  learning_rate: 4.0e-4
  weight_decay: 0.1
  betas:
  - 0.9
  - 0.95
  metrics_log_interval: 10

scheduler:
  name: cosine_with_warmup
  t_warmup: 2000
  alpha_f: 0.1

tokenizer:
  identifier: OLMo/tokenizers/allenai_eleuther-ai-gpt-neox-20b-pii-special.json
  truncate_direction: right

save_folder: pre_training_results/olma_2layer/dolma/22B
save_overwrite: True
# Sharded checkpoints (best for restarts)
save_interval: 1000
save_num_checkpoints_to_keep: 9
# Unsharded checkpoints (for final storage)
save_interval_unsharded: 10000
save_num_unsharded_checkpoints_to_keep: -1

load_path: null

max_duration: 1ep  
global_train_batch_size: 2048
device_train_microbatch_size: 16
precision: amp_bf16

fsdp:
  wrapping_strategy: null
  precision: mixed

max_grad_norm: 1.0
max_grad_norm_ratio: null

speed_monitor:
  window_size: 20

eval_interval: 10000 # actually steps = ~7000, so we don't run eval on-line
eval_subset_num_batches: -1
device_eval_batch_size: ${device_train_microbatch_size}
evaluators:
  # lump all the small datasets together (we still get separate metrics).
  - label: v3-small-ppl-validation
    data:
      num_workers: 0
      drop_last: true
      datasets:
        v3-small-c4_en-validation:
          - data/dolma/olma_1B_data/val_data/v3-small-c4_en-validation/part-0-00000.npy

  - label: v2-small-ppl-validation
    data:
      num_workers: 0
      drop_last: true
      datasets:
        v2-small-4chan-validation:
          - data/dolma/olma_1B_data/val_data/v2-small-4chan-validation/val.npy

  # - label: piqa
  #   type: downstream

  # - label: hellaswag
  #   type: downstream

  # - label: winogrande
  #   type: downstream

  # - label: openbook_qa
  #   type: downstream

  # - label: boolq  # requires implemention of the pmi_dc matrix
    # type: downstream

  # - label: sciq
  #   type: downstream

  # - label: arc_easy
  #   type: downstream

  # - label: arc_challenge  # requires implemention of the pmi_dc matrix
  #   type: downstream

  # - label: copa
  #   type: downstream

  # - label: rte
  #   type: downstream

  # - label: commitment_bank
  #   type: downstream

  # - label: mrpc
  #   type: downstream

  # - label: sst2
  #   type: downstream

data:
  pad_direction: right
  num_workers: 0
  drop_last: true
  pin_memory: true
  prefetch_factor: 16
  persistent_workers: true
  timeout: 0
  paths:
    - /data1/xkzhu/datasets/dolma_sampled_25B_tokenized/00_00000.npy
    - /data1/xkzhu/datasets/dolma_sampled_25B_tokenized/00_00001.npy
    - /data1/xkzhu/datasets/dolma_sampled_25B_tokenized/01_00000.npy
    - /data1/xkzhu/datasets/dolma_sampled_25B_tokenized/01_00001.npy
    - /data1/xkzhu/datasets/dolma_sampled_25B_tokenized/02_00000.npy
    - /data1/xkzhu/datasets/dolma_sampled_25B_tokenized/02_00001.npy
    - /data1/xkzhu/datasets/dolma_sampled_25B_tokenized/03_00000.npy
    - /data1/xkzhu/datasets/dolma_sampled_25B_tokenized/03_00001.npy
    - /data1/xkzhu/datasets/dolma_sampled_25B_tokenized/04_00000.npy
    - /data1/xkzhu/datasets/dolma_sampled_25B_tokenized/04_00001.npy
    - /data1/xkzhu/datasets/dolma_sampled_25B_tokenized/05_00000.npy
    - /data1/xkzhu/datasets/dolma_sampled_25B_tokenized/05_00001.npy
    - /data1/xkzhu/datasets/dolma_sampled_25B_tokenized/06_00000.npy
    - /data1/xkzhu/datasets/dolma_sampled_25B_tokenized/06_00001.npy
    - /data1/xkzhu/datasets/dolma_sampled_25B_tokenized/07_00000.npy
    - /data1/xkzhu/datasets/dolma_sampled_25B_tokenized/07_00001.npy
    - /data1/xkzhu/datasets/dolma_sampled_25B_tokenized/08_00000.npy
    - /data1/xkzhu/datasets/dolma_sampled_25B_tokenized/08_00001.npy
    - /data1/xkzhu/datasets/dolma_sampled_25B_tokenized/09_00000.npy
    - /data1/xkzhu/datasets/dolma_sampled_25B_tokenized/09_00001.npy
    - /data1/xkzhu/datasets/dolma_sampled_25B_tokenized/10_00000.npy
    - /data1/xkzhu/datasets/dolma_sampled_25B_tokenized/10_00001.npy
    - /data1/xkzhu/datasets/dolma_sampled_25B_tokenized/11_00000.npy
    - /data1/xkzhu/datasets/dolma_sampled_25B_tokenized/11_00001.npy
    - /data1/xkzhu/datasets/dolma_sampled_25B_tokenized/12_00000.npy
    - /data1/xkzhu/datasets/dolma_sampled_25B_tokenized/13_00000.npy
    - /data1/xkzhu/datasets/dolma_sampled_25B_tokenized/13_00001.npy
    - /data1/xkzhu/datasets/dolma_sampled_25B_tokenized/14_00000.npy
    - /data1/xkzhu/datasets/dolma_sampled_25B_tokenized/14_00001.npy
    - /data1/xkzhu/datasets/dolma_sampled_25B_tokenized/15_00000.npy
    - /data1/xkzhu/datasets/dolma_sampled_25B_tokenized/15_00001.npy
    - /data1/xkzhu/datasets/dolma_sampled_25B_tokenized/16_00000.npy
    - /data1/xkzhu/datasets/dolma_sampled_25B_tokenized/16_00001.npy
    - /data1/xkzhu/datasets/dolma_sampled_25B_tokenized/17_00000.npy
    - /data1/xkzhu/datasets/dolma_sampled_25B_tokenized/17_00001.npy
    - /data1/xkzhu/datasets/dolma_sampled_25B_tokenized/18_00000.npy
    - /data1/xkzhu/datasets/dolma_sampled_25B_tokenized/18_00001.npy
    - /data1/xkzhu/datasets/dolma_sampled_25B_tokenized/19_00000.npy
    - /data1/xkzhu/datasets/dolma_sampled_25B_tokenized/19_00001.npy
    - /data1/xkzhu/datasets/dolma_sampled_25B_tokenized/20_00000.npy
    - /data1/xkzhu/datasets/dolma_sampled_25B_tokenized/20_00001.npy
    - /data1/xkzhu/datasets/dolma_sampled_25B_tokenized/20_00002.npy
    - /data1/xkzhu/datasets/dolma_sampled_25B_tokenized/21_00000.npy
    - /data1/xkzhu/datasets/dolma_sampled_25B_tokenized/22_00000.npy
    - /data1/xkzhu/datasets/dolma_sampled_25B_tokenized/22_00001.npy
    - /data1/xkzhu/datasets/dolma_sampled_25B_tokenized/23_00000.npy
    - /data1/xkzhu/datasets/dolma_sampled_25B_tokenized/23_00001.npy
    - /data1/xkzhu/datasets/dolma_sampled_25B_tokenized/24_00000.npy
    - /data1/xkzhu/datasets/dolma_sampled_25B_tokenized/24_00001.npy
    - /data1/xkzhu/datasets/dolma_sampled_25B_tokenized/25_00000.npy
    - /data1/xkzhu/datasets/dolma_sampled_25B_tokenized/25_00001.npy
    - /data1/xkzhu/datasets/dolma_sampled_25B_tokenized/26_00000.npy
    - /data1/xkzhu/datasets/dolma_sampled_25B_tokenized/26_00001.npy
    - /data1/xkzhu/datasets/dolma_sampled_25B_tokenized/27_00000.npy
    - /data1/xkzhu/datasets/dolma_sampled_25B_tokenized/27_00001.npy
    - /data1/xkzhu/datasets/dolma_sampled_25B_tokenized/28_00000.npy
    - /data1/xkzhu/datasets/dolma_sampled_25B_tokenized/28_00001.npy
    - /data1/xkzhu/datasets/dolma_sampled_25B_tokenized/29_00000.npy
    - /data1/xkzhu/datasets/dolma_sampled_25B_tokenized/29_00001.npy
    - /data1/xkzhu/datasets/dolma_sampled_25B_tokenized/30_00000.npy
    - /data1/xkzhu/datasets/dolma_sampled_25B_tokenized/30_00001.npy
    - /data1/xkzhu/datasets/dolma_sampled_25B_tokenized/31_00000.npy
    - /data1/xkzhu/datasets/dolma_sampled_25B_tokenized/31_00001.npy
    - /data1/xkzhu/datasets/dolma_sampled_25B_tokenized/32_00000.npy
    - /data1/xkzhu/datasets/dolma_sampled_25B_tokenized/32_00001.npy
    - /data1/xkzhu/datasets/dolma_sampled_25B_tokenized/33_00000.npy
    - /data1/xkzhu/datasets/dolma_sampled_25B_tokenized/33_00001.npy
    - /data1/xkzhu/datasets/dolma_sampled_25B_tokenized/34_00000.npy
    - /data1/xkzhu/datasets/dolma_sampled_25B_tokenized/35_00000.npy
    - /data1/xkzhu/datasets/dolma_sampled_25B_tokenized/35_00001.npy

